apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  claimRef:
    name: database-pvc
    namespace: default
  