apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: default
spec:
  storageClassName: "" # Static provisioning
  volumeName: database-pv # This must match the name of the PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi